### ISSUE TITLE
@scena/react-store resolve error on editor start

### ISSUE THREAD

**Issue by gulyabaniTR** [daybrush/scena#19]
![image](https://user-images.githubusercontent.com/15141076/223102461-20d6a637-cf05-4655-bf37-ebaec81efc16.png)

npm i root, packages/scena-store and packages/scena-editor folder.

tried  on root folder and editor packages/editor folder. both are now working cause react-store module

**Comment by daybrush** [comment]
@gulyabaniTR 

The scenea repository uses `yarn workspace`.


1. first intall with `yarn`

```sh
$yarn
```
2. start server
```sh
$ yarn start
```

**Comment by gulyabaniTR** [comment]
it worked, thank you ✌
