### ISSUE TITLE
hi daybrush, do you continue maintain Selecto project?

### ISSUE THREAD

**Issue by leeboo** [daybrush/scena#5]
hi daybrush, do you continue maintain Selecto project?
git link is broken

**Comment by daybrush** [comment]
@leeboo 

Perhaps it will be released later this month.

**Comment by leeboo** [comment]
amazing
thanks

**Comment by daybrush** [comment]
@leeboo 

Selecto 1.0.0 is released. Thank you :)
https://github.com/daybrush/selecto
